import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  bookmakers: defineTable({
    slug: v.string(),
    name: v.string(),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("archived")),
    brandColor: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    source: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  bookmaker_offers: defineTable({
    bookmakerSlug: v.string(),
    slug: v.string(),
    title: v.string(),
    summary: v.string(),
    qualifyingStake: v.number(),
    totalFreeBetValue: v.number(),
    standardFreeBetValue: v.number(),
    betBuilderFreeBetValue: v.number(),
    accumulatorFreeBetValue: v.number(),
    expectedProfit: v.number(),
    currency: v.string(),
    active: v.boolean(),
    sourceCsvRow: v.any(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]).index("by_bookmakerSlug", ["bookmakerSlug"]),

  bookmaker_offer_rules: defineTable({
    bookmakerSlug: v.string(),
    offerSlug: v.string(),
    sportKeys: v.array(v.string()),
    marketKeys: v.array(v.string()),
    minBackOdds: v.optional(v.number()),
    minStake: v.optional(v.number()),
    expiryDays: v.optional(v.number()),
    qualifyingWindowDays: v.optional(v.number()),
    termsUrl: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_offerSlug", ["offerSlug"]),

  competitions: defineTable({
    sportKey: v.string(),
    slug: v.string(),
    name: v.string(),
    country: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  participants: defineTable({
    slug: v.string(),
    name: v.string(),
    competitionSlug: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),

  events: defineTable({
    sportKey: v.string(),
    competitionSlug: v.string(),
    externalSource: v.union(v.literal("virgin_bet"), v.literal("smarkets")),
    externalId: v.string(),
    slug: v.string(),
    name: v.string(),
    startsAt: v.string(),
    status: v.union(
      v.literal("scheduled"),
      v.literal("live"),
      v.literal("settled"),
      v.literal("suspended"),
    ),
    homeParticipantSlug: v.optional(v.string()),
    awayParticipantSlug: v.optional(v.string()),
    metadata: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]).index("by_externalId", ["externalSource", "externalId"]),

  markets: defineTable({
    eventSlug: v.string(),
    marketKey: v.string(),
    label: v.string(),
    status: v.union(v.literal("open"), v.literal("closed"), v.literal("suspended")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_eventSlug", ["eventSlug"]),

  outcomes: defineTable({
    marketSlug: v.string(),
    outcomeKey: v.string(),
    label: v.string(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_marketSlug", ["marketSlug"]),

  bookmaker_outcome_odds_snapshots: defineTable({
    bookmakerSlug: v.string(),
    offerSlug: v.optional(v.string()),
    eventSlug: v.string(),
    marketKey: v.string(),
    outcomeKey: v.string(),
    odds: v.number(),
    scrapedAt: v.string(),
    sourceUrl: v.optional(v.string()),
    rawPayload: v.optional(v.string()),
    confidence: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_event_market_outcome", ["eventSlug", "marketKey", "outcomeKey"]),

  exchange_outcome_odds_snapshots: defineTable({
    exchange: v.literal("smarkets"),
    eventSlug: v.string(),
    marketKey: v.string(),
    outcomeKey: v.string(),
    layOdds: v.number(),
    liquidity: v.number(),
    commissionRate: v.number(),
    scrapedAt: v.string(),
    sourceUrl: v.optional(v.string()),
    rawPayload: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_event_market_outcome", ["eventSlug", "marketKey", "outcomeKey"]),

  current_best_prices: defineTable({
    eventSlug: v.string(),
    marketKey: v.string(),
    outcomeKey: v.string(),
    bookmakerSlug: v.string(),
    offerSlug: v.optional(v.string()),
    bookmakerBackOdds: v.number(),
    exchangeLayOdds: v.number(),
    liquidity: v.number(),
    commissionRate: v.number(),
    mappingConfidence: v.string(),
    oneClickEligible: v.boolean(),
    qualifyingLoss: v.number(),
    projectedFreeBetProfit: v.number(),
    netExpectedProfit: v.number(),
    priceUpdatedAt: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_event_market_outcome", ["eventSlug", "marketKey", "outcomeKey"]),

  matched_betting_candidates: defineTable({
    candidateId: v.string(),
    kind: v.string(),
    bookmakerSlug: v.string(),
    offerSlug: v.string(),
    eventSlug: v.string(),
    marketKey: v.string(),
    outcomeKey: v.string(),
    bookmakerBackOdds: v.number(),
    exchangeLayOdds: v.number(),
    liquidity: v.number(),
    commissionRate: v.number(),
    mappingConfidence: v.string(),
    qualifyingLoss: v.number(),
    projectedFreeBetProfit: v.number(),
    netExpectedProfit: v.number(),
    status: v.union(
      v.literal("draft"),
      v.literal("eligible"),
      v.literal("saved"),
      v.literal("placed"),
      v.literal("completed"),
      v.literal("stale"),
    ),
    rankingScore: v.number(),
    badges: v.array(v.string()),
    oneClickEligible: v.boolean(),
    notes: v.optional(v.string()),
    freshnessAt: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_offerSlug", ["offerSlug"]).index("by_candidateId", ["candidateId"]),

  dashboards: defineTable({
    userId: v.string(),
    name: v.string(),
    defaultDashboard: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_userId", ["userId"]),

  dashboard_entries: defineTable({
    dashboardId: v.string(),
    candidateId: v.string(),
    status: v.union(v.literal("saved"), v.literal("planned"), v.literal("placed"), v.literal("completed")),
    notes: v.optional(v.string()),
    stake: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_dashboardId", ["dashboardId"]),

  user_qualifying_bets: defineTable({
    userId: v.string(),
    offerSlug: v.string(),
    candidateId: v.optional(v.string()),
    status: v.union(v.literal("planned"), v.literal("placed"), v.literal("settled")),
    backStake: v.number(),
    layStake: v.optional(v.number()),
    liability: v.optional(v.number()),
    qualifyingLoss: v.optional(v.number()),
    placedAt: v.optional(v.string()),
    settledAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_userId", ["userId"]),

  user_lay_bets: defineTable({
    userId: v.string(),
    candidateId: v.string(),
    smarketsOrderId: v.optional(v.string()),
    status: v.union(v.literal("draft"), v.literal("preflighted"), v.literal("confirmed"), v.literal("placed"), v.literal("failed")),
    layStake: v.number(),
    liability: v.number(),
    placedAt: v.optional(v.string()),
    confirmedAt: v.optional(v.string()),
    rawRequest: v.optional(v.string()),
    rawResponse: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_userId", ["userId"]),

  user_free_bets: defineTable({
    userId: v.string(),
    offerSlug: v.string(),
    candidateId: v.optional(v.string()),
    status: v.union(v.literal("available"), v.literal("selected"), v.literal("placed"), v.literal("settled"), v.literal("used")),
    freeBetStake: v.number(),
    expectedProfit: v.number(),
    selectedAt: v.optional(v.string()),
    placedAt: v.optional(v.string()),
    settledAt: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_userId", ["userId"]),

  user_smarkets_accounts: defineTable({
    userId: v.string(),
    accountName: v.string(),
    encryptedToken: v.string(),
    tokenFingerprint: v.string(),
    encryptionVersion: v.string(),
    status: v.union(v.literal("connected"), v.literal("expired"), v.literal("revoked")),
    connectedAt: v.string(),
    lastVerifiedAt: v.optional(v.string()),
    expiresAt: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_userId", ["userId"]),

  scrape_runs: defineTable({
    source: v.union(v.literal("virgin_bet"), v.literal("smarkets")),
    jobName: v.string(),
    status: v.union(v.literal("running"), v.literal("success"), v.literal("failed"), v.literal("partial")),
    startedAt: v.string(),
    finishedAt: v.optional(v.string()),
    error: v.optional(v.string()),
    payloadCount: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_source", ["source"]),

  raw_scrape_snapshots: defineTable({
    source: v.union(v.literal("virgin_bet"), v.literal("smarkets")),
    jobName: v.string(),
    entityType: v.string(),
    entityKey: v.string(),
    scrapedAt: v.string(),
    rawPayload: v.string(),
    parsedOk: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_entity", ["entityType", "entityKey"]),

  event_mappings: defineTable({
    bookmakerSlug: v.optional(v.string()),
    exchangeSource: v.literal("smarkets"),
    bookmakerEventName: v.string(),
    exchangeEventName: v.string(),
    eventSlug: v.optional(v.string()),
    confidence: v.string(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    approvedBy: v.optional(v.string()),
    approvedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]),

  market_mappings: defineTable({
    bookmakerSlug: v.optional(v.string()),
    exchangeSource: v.literal("smarkets"),
    bookmakerMarketLabel: v.string(),
    exchangeMarketLabel: v.string(),
    marketKey: v.optional(v.string()),
    confidence: v.string(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    approvedBy: v.optional(v.string()),
    approvedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]),

  outcome_mappings: defineTable({
    bookmakerSlug: v.optional(v.string()),
    exchangeSource: v.literal("smarkets"),
    bookmakerOutcomeLabel: v.string(),
    exchangeOutcomeLabel: v.string(),
    outcomeKey: v.optional(v.string()),
    confidence: v.string(),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    approvedBy: v.optional(v.string()),
    approvedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]),

  admin_overrides: defineTable({
    entityType: v.string(),
    entityKey: v.string(),
    overrideKey: v.string(),
    overrideValue: v.string(),
    active: v.boolean(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_entity", ["entityType", "entityKey"]),
});
