/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSmarketsRouteImport } from './routes/settings.smarkets'
import { Route as OffersBookmakerSlugRouteImport } from './routes/offers.$bookmakerSlug'
import { Route as DashboardDashboardIdRouteImport } from './routes/dashboard.$dashboardId'
import { Route as OffersBookmakerSlugOfferSlugOpportunitiesRouteImport } from './routes/offers.$bookmakerSlug.$offerSlug.opportunities'

const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSmarketsRoute = SettingsSmarketsRouteImport.update({
  id: '/settings/smarkets',
  path: '/settings/smarkets',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersBookmakerSlugRoute = OffersBookmakerSlugRouteImport.update({
  id: '/$bookmakerSlug',
  path: '/$bookmakerSlug',
  getParentRoute: () => OffersRoute,
} as any)
const DashboardDashboardIdRoute = DashboardDashboardIdRouteImport.update({
  id: '/$dashboardId',
  path: '/$dashboardId',
  getParentRoute: () => DashboardRoute,
} as any)
const OffersBookmakerSlugOfferSlugOpportunitiesRoute =
  OffersBookmakerSlugOfferSlugOpportunitiesRouteImport.update({
    id: '/$offerSlug/opportunities',
    path: '/$offerSlug/opportunities',
    getParentRoute: () => OffersBookmakerSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRouteWithChildren
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/offers/$bookmakerSlug': typeof OffersBookmakerSlugRouteWithChildren
  '/settings/smarkets': typeof SettingsSmarketsRoute
  '/offers/$bookmakerSlug/$offerSlug/opportunities': typeof OffersBookmakerSlugOfferSlugOpportunitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRouteWithChildren
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/offers/$bookmakerSlug': typeof OffersBookmakerSlugRouteWithChildren
  '/settings/smarkets': typeof SettingsSmarketsRoute
  '/offers/$bookmakerSlug/$offerSlug/opportunities': typeof OffersBookmakerSlugOfferSlugOpportunitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRouteWithChildren
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/offers/$bookmakerSlug': typeof OffersBookmakerSlugRouteWithChildren
  '/settings/smarkets': typeof SettingsSmarketsRoute
  '/offers/$bookmakerSlug/$offerSlug/opportunities': typeof OffersBookmakerSlugOfferSlugOpportunitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/offers'
    | '/dashboard/$dashboardId'
    | '/offers/$bookmakerSlug'
    | '/settings/smarkets'
    | '/offers/$bookmakerSlug/$offerSlug/opportunities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/offers'
    | '/dashboard/$dashboardId'
    | '/offers/$bookmakerSlug'
    | '/settings/smarkets'
    | '/offers/$bookmakerSlug/$offerSlug/opportunities'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/offers'
    | '/dashboard/$dashboardId'
    | '/offers/$bookmakerSlug'
    | '/settings/smarkets'
    | '/offers/$bookmakerSlug/$offerSlug/opportunities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRouteWithChildren
  SettingsSmarketsRoute: typeof SettingsSmarketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/smarkets': {
      id: '/settings/smarkets'
      path: '/settings/smarkets'
      fullPath: '/settings/smarkets'
      preLoaderRoute: typeof SettingsSmarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$bookmakerSlug': {
      id: '/offers/$bookmakerSlug'
      path: '/$bookmakerSlug'
      fullPath: '/offers/$bookmakerSlug'
      preLoaderRoute: typeof OffersBookmakerSlugRouteImport
      parentRoute: typeof OffersRoute
    }
    '/dashboard/$dashboardId': {
      id: '/dashboard/$dashboardId'
      path: '/$dashboardId'
      fullPath: '/dashboard/$dashboardId'
      preLoaderRoute: typeof DashboardDashboardIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/offers/$bookmakerSlug/$offerSlug/opportunities': {
      id: '/offers/$bookmakerSlug/$offerSlug/opportunities'
      path: '/$offerSlug/opportunities'
      fullPath: '/offers/$bookmakerSlug/$offerSlug/opportunities'
      preLoaderRoute: typeof OffersBookmakerSlugOfferSlugOpportunitiesRouteImport
      parentRoute: typeof OffersBookmakerSlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardIdRoute: typeof DashboardDashboardIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardIdRoute: DashboardDashboardIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OffersBookmakerSlugRouteChildren {
  OffersBookmakerSlugOfferSlugOpportunitiesRoute: typeof OffersBookmakerSlugOfferSlugOpportunitiesRoute
}

const OffersBookmakerSlugRouteChildren: OffersBookmakerSlugRouteChildren = {
  OffersBookmakerSlugOfferSlugOpportunitiesRoute:
    OffersBookmakerSlugOfferSlugOpportunitiesRoute,
}

const OffersBookmakerSlugRouteWithChildren =
  OffersBookmakerSlugRoute._addFileChildren(OffersBookmakerSlugRouteChildren)

interface OffersRouteChildren {
  OffersBookmakerSlugRoute: typeof OffersBookmakerSlugRouteWithChildren
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersBookmakerSlugRoute: OffersBookmakerSlugRouteWithChildren,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRouteWithChildren,
  SettingsSmarketsRoute: SettingsSmarketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
